name: Run Bats Tests

on: [push, pull_request]

jobs:
  bats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Bats
        run: sudo apt-get install -y bats

      - name: Make flash-truth.sh executable
        run: chmod +x flash-truth.sh

      - name: Run Bats tests
        run: bats tests/
